name: golangci-lint

on: [push]

permissions: 
  contents: read

jobs: 
  golangci: 
    name: lint
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v5
      - uses: actions/setup-go@v6
        with: 
          go-version: "1.25"
          cache: false
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v8
        with: 
          version: latest
